services:
  postgres-db:
    image: postgres:18.3-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - smart_home_postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-home
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5

  kafka:
    image: confluentinc/confluent-local:7.4.3
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092" # for client connections
      - "9101:9101" # JMX
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      CLUSTER_ID: 'K0EA9p0yEe6MkAAAAkKsEg'

  kafka-init-topics:
    image: confluentinc/confluent-local:7.4.3
    container_name: kafka-init-topics
    depends_on:
      - kafka
    command: "bash -c \
                'kafka-topics --create --topic telemetry.sensors.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.snapshots.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092 && \
                kafka-topics --create --topic telemetry.hubs.v1 \
                             --partitions 1 --replication-factor 1 --if-not-exists \
                             --bootstrap-server kafka:29092'"
    init: true

  discovery-server:
    build:
      context: .
      dockerfile: infra/discovery-server/Dockerfile
    ports:
      - "8761:8761"
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8761/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  config-server:
    build:
      context: .
      dockerfile: infra/config-server/Dockerfile
    ports:
      - "8888:8888"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      discovery-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8888/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  shopping-cart:
    build:
      context: .
      dockerfile: commerce/shopping-cart/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8081/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  shopping-store:
    build:
      context: .
      dockerfile: commerce/shopping-store/Dockerfile
    ports:
      - "8082:8082"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8082/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  warehouse:
    build:
      context: .
      dockerfile: commerce/warehouse/Dockerfile
    ports:
      - "8083:8083"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8083/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  collector:
    build:
      context: .
      dockerfile: telemetry/collector/Dockerfile
    ports:
      - "10089:10089"
      - "59091:59091"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:10089/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  analyzer:
    build:
      context: .
      dockerfile: telemetry/analyzer/Dockerfile
    ports:
      - "10091:10091"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:10091/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

  aggregator:
    build:
      context: .
      dockerfile: telemetry/aggregator/Dockerfile
    ports:
      - "10090:10090"
    restart: unless-stopped
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://discovery-server:8761/eureka/
    depends_on:
      config-server:
        condition: service_healthy

    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:10090/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      start_period: 30s
      retries: 5

volumes:
  smart_home_postgres_data:
