kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER:localhost:9092}
  consumer:
    snapshot:
      topics: ["telemetry.snapshots.v1"]
      keyDeserializerClass: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializerClass: ru.yandex.practicum.serialization.SnapshotAvroDeserializer
      clientId: snapshot-consumer
      groupId: snapshot-group
      maxPollRecords: 25
      consumeTimeout: 5000

    hub-event:
      topics: ["telemetry.hubs.v1"]
      keyDeserializerClass: org.apache.kafka.common.serialization.StringDeserializer
      valueDeserializerClass: ru.yandex.practicum.serialization.HubEventAvroDeserializer
      clientId: hub-event-consumer
      groupId: hub-event-group
      maxPollRecords: 25
      consumeTimeout: 5000
